# Generated by Django 4.2.2 on 2023-07-14 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_alter_venta_mesa_monto_mesa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venta_mesa",
            name="fecha_venta",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
